@RiverBooks.Web_HostAddress = https://localhost:7149

GET {{RiverBooks.Web_HostAddress}}/api/books/
Accept: application/json
###

@BookID=741f0053-d934-4868-a890-f40217a5b1c5
GET {{RiverBooks.Web_HostAddress}}/api/books/{{BookID}}
Accept: application/json
###

POST {{RiverBooks.Web_HostAddress}}/api/books/
Accept: application/json
Content-Type: application/json

{
  "Id": "593c39f7-851e-41db-b664-29976f26ddc5",
  "Title": "The Art of War",
  "Author": "Sun Tzu",
  "Price": 15.99
}
###

POST {{RiverBooks.Web_HostAddress}}/api/books/593c39f7-851e-41db-b664-29976f26ddc5/pricehistory
Accept: application/json
Content-Type: application/json

{
  "Id": "593c39f7-851e-41db-b664-29976f26ddc5",
  "newPrice": -6.99
}
###

DELETE {{RiverBooks.Web_HostAddress}}/api/books/593c39f7-851e-41db-b664-29976f26ddc5
Accept: application/json

###

POST {{RiverBooks.Web_HostAddress}}/users
Accept: application/json
Content-Type: application/json

{
  "Email": "gusflopes@hublaw.com.br",
  "Password": "Pass@word1"
}

###

POST {{RiverBooks.Web_HostAddress}}/users/login
Accept: application/json
Content-Type: application/json

{
  "Email": "gusflopes@hublaw.com.br",
  "Password": "Pass@word1"
}

###

@token=eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbEFkZHJlc3MiOiJndXNmbG9wZXNAaHVibGF3LmNvbS5iciIsImlzcyI6IlJpdmVyQm9va3MiLCJpYXQiOjE3MTMxNDkxMTIsImV4cCI6MTcxMzE1MjcxMiwibmJmIjoxNzEzMTQ5MTEyfQ.C2Q7rhIiAoKNIZhVr9IpjvwsYK7DnyjTjv7WIzZPqC8





# Add Item to Cart
POST {{RiverBooks.Web_HostAddress}}/cart
Accept: text/plain
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "BookId": "741f0053-d934-4868-a890-f40217a5b1c5",
  "Quantity": 0
}

###

#List items in cart
GET {{RiverBooks.Web_HostAddress}}/cart
Accept: application/json
Authorization: Bearer {{token}}

###

@ShippingAddressID=90714529-408e-4d2f-9781-f392d2483098
@BillingAddressID=90714529-408e-4d2f-9781-f392d2483098

# Checkout
POST {{RiverBooks.Web_HostAddress}}/cart/checkout
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "ShippingAddressId": "{{ShippingAddressID}}",
  "BillingAddressId": "{{BillingAddressID}}"
}

###

# List All Orders
GET {{RiverBooks.Web_HostAddress}}/orders
Accept: application/json
Authorization: Bearer {{token}}

###

# List Addresses
GET {{RiverBooks.Web_HostAddress}}/users/addresses
Accept: application/json
Authorization: Bearer {{token}}

###

# Add Address
POST {{RiverBooks.Web_HostAddress}}/users/addresses
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Street1": "Rua dos Bobos, 123456",
  "Street2": "",
  "City": "São Paulo",
  "State": "SP",
  "ZipCode": "12345-678",
  "Country": "Brazil"
}

###

# Flush Cache
DELETE {{RiverBooks.Web_HostAddress}}/orders/addresses
Accept: application/json
Authorization: Bearer {{token}}

###